crudapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import login_view,index

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login_page"),
    path("",views.login_view, name="login"),
    path("index/", views.index, name="home"),
    path("add/", views.add_patient, name="add"),
    path("edit/<int:id>/", views.edit_patient, name="edit"),
    path("delete/<int:id>/", views.delete_patient, name="delete"),
    path('logout/',auth_views.LogoutView.as_view(next_page='login'),name='logout'),
]

healthcareproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudapp.urls'))
]

crudapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # ✅ add this
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    symptoms = models.CharField(max_length=200)
    suggestion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

crudapp/forms.py
from django import forms
from .models import Patient

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ["name", "age", "symptoms"]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Enter your name'}),
            'age': forms.NumberInput(attrs={'class': 'form-input', 'placeholder': 'Enter your age'}),
            'symptoms': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'e.g. fever, cold'}),
        }

crudapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .models import Patient
from .forms import PatientForm
import csv, os
from django.conf import settings

# Load CSV to dictionary
def load_suggestions():
    filepath = os.path.join(settings.BASE_DIR, "symptom_suggestions.csv")
    suggestions = {}
    with open(filepath, "r") as file:
        reader = csv.DictReader(file)
        for row in reader:
            key = row["symptom"].lower().replace('"', '').strip()
            value = row["suggestion"].replace('"', '').strip()
            suggestions[key] = value
    return suggestions

def match_suggestion(symptoms):
    data = load_suggestions()
    symptoms = symptoms.lower()

    for symptom_list, suggestion in data.items():
        symptom_list = symptom_list.lower()
        if any(s.strip() in symptom_list for s in symptoms.split(",")):
            return suggestion
    
    return "Im not aware of it.Please consult a doctor!"
@login_required(login_url="/login/")
def index(request):
    patients = Patient.objects.filter(user=request.user)
    return render(request, "index.html", {"patients": patients})

def add_patient(request):
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.user = request.user   # ✅ store who created
            patient.suggestion = match_suggestion(patient.symptoms)
            patient.save()
            return redirect('home')
    else:
        form = PatientForm()
    return render(request, "add.html", {"form": form})

def edit_patient(request, id):
    patient = get_object_or_404(Patient, id=id)

    if patient.user != request.user:
        return HttpResponse("Unauthorized", status=401)
    
    if request.method == "POST":
        form = PatientForm(request.POST, instance=patient)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.suggestion = match_suggestion(patient.symptoms)
            patient.save()
            return redirect('home')
    else:
        form = PatientForm(instance=patient)
    return render(request, "edit.html", {"form": form})

def delete_patient(request, id):
    patient = get_object_or_404(Patient, id=id)
    
    if patient.user != request.user:
        return HttpResponse("Unauthorized", status=401)

    
    patient.delete()
    return redirect('home')



def register(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already exists!")
        else:
            user = User.objects.create_user(username=username, password=password)
            user.save()
            return redirect("login")  

    return render(request, "register.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("home")  
        else:
            messages.error(request,'Invalid username or password!')
            
    return render(request, "login.html")

crudapp/templates/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h2>Add Patient</h2>
<!--<form method="POST" class="form-container">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
    <a href="{% url 'home' %}" class="back">Back</a>
</form>-->
<form method="POST" class="form-container">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
    </div>

    <div class="form-group">
        <label for="id_age">Age:</label>
        {{ form.age }}
    </div>

    <div class="form-group">
        <label for="id_symptoms">Symptoms:</label>
        {{ form.symptoms }}
    </div>

    <button type="submit" >Save</button>
    <a href="{% url 'home' %}" class="back">Back</a>
</form>


</body>
</html>

crudapp/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h2>Edit Patient</h2>
<!--<form method="POST" class="form-container">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Update</button><br>
    <a href="{% url 'home' %}" class="back">Back</a>
</form>-->
<form method="POST" class="form-container">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
    </div>

    <div class="form-group">
        <label for="id_age">Age:</label>
        {{ form.age }}
    </div>

    <div class="form-group">
        <label for="id_symptoms">Symptoms:</label>
        {{ form.symptoms }}
    </div>

    <button type="submit" >Update</button>
    <a href="{% url 'home' %}" class="back">Back</a>
</form>

</body>
</html>

crudapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    
    <div style="text-align: center; margin-bottom: 15px;">
        <h2>Health Suggestion System</h2> 
        <a href="{% url 'add' %}" target="_self" class="add_patient">Add Patient</a> |
        <a href="{% url 'logout' %}" target="_self" class="logout">Logout</a>
        <table border="1">
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Symptoms</th>
                <th>Suggestion</th>
                <th>Actions</th>
            </tr>
            
            {% for p in patients %}
            <tr>
                <td>{{ p.name }}</td>
                <td>{{ p.age }}</td>
                <td>{{ p.symptoms }}</td>
                <td>{{ p.suggestion }}</td>
                <td>
                    <a href="{% url 'edit' p.id %}">Update</a> |
                    <a href="{% url 'delete' p.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
            </table>
    </div>



</body>
</html>

crudapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login | Health Suggestion System</title>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f7fa;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .container {
        background: white;
        width: 380px;
        padding: 25px;
        border-radius: 8px;
        box-shadow: 0px 0px 12px rgba(0,0,0,0.2);
    }

    h2 {
        text-align: center;
        color: #0066cc;
        margin-bottom: 20px;
        font-size: 24px;
    }

    label {
        font-size: 14px;
        font-weight: bold;
        color: #333;
    }

    input {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 15px;
    }

    button {
        width: 100%;
        padding: 10px;
        background-color: #0066cc;
        color: white;
        border: none;
        font-size: 16px;
        cursor: pointer;
        border-radius: 5px;
    }

    button:hover {
        background-color: #004c99;
    }

    .footer {
        text-align: center;
        margin-top: 10px;
        font-size: 14px;
    }

    .footer a {
        color: #0066cc;
        text-decoration: none;
        font-weight: bold;
    }
    .alert {
    color: #fff;
    background-color: #dc3545;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
    text-align: center;
    }
</style>
</head>

<body>
<div class="container">
    <h2>Login</h2>
    {% if messages %}
        {% for message in messages %}
            <div class="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <form action="{%  url 'login' %}" method="POST">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" name="username" placeholder="Enter Username" required>

        <label>Password</label>
        <input type="password" name="password" placeholder="Enter Password" required>

        <button type="submit" >Login</button>
    </form>

    <div class="footer">
        <p>Don't have an account?
        <a href="{% url 'register' %}">Register</a></p>
    </div>
</div>
</body>
</html>

crudapp/templates/register.html
<!DOCTYPE html>
<html>
<head>
<title>Register</title>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f7fa;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .container {
        background: white;
        width: 380px;
        padding: 25px;
        border-radius: 8px;
        box-shadow: 0px 0px 12px rgba(0,0,0,0.2);
    }

    h2 {
        text-align: center;
        color: #0066cc;
        margin-bottom: 20px;
        font-size: 24px;
    }

    label {
        font-size: 14px;
        font-weight: bold;
        color: #333;
    }

    input {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 15px;
    }

    button {
        width: 100%;
        padding: 10px;
        background-color: #0066cc;
        color: white;
        border: none;
        font-size: 16px;
        cursor: pointer;
        border-radius: 5px;
    }

    button:hover {
        background-color: #004c99;
    }

    .footer {
        text-align: center;
        margin-top: 10px;
        font-size: 14px;
    }

    .footer a {
        color: #0066cc;
        text-decoration: none;
        font-weight: bold;
    }
    .alert {
    color: #fff;
    background-color: #dc3545;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
    text-align: center;
    }
</style>

</head>
<body>
<div class="container">
<h2>Register</h2>
{% if messages %}
    {% for message in messages %}
        <div class="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<form method="POST">
    {% csrf_token %}
    <label>Username</label>
    <input type="text" name="username" placeholder="Enter Username" required><br><br>
    <label>Password</label>
    <input type="password" name="password" placeholder="Enter Password" required><br><br>
    <button type="submit">Register</button>
</form>
<div class="footer">
<p>Already have an account?
<a href="{% url 'login' %}">Login</a></p>
</div>
</div>
</body>
</html>